// <auto-generated />
namespace ParkingManager.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addPayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPayment));
        
        string IMigrationMetadata.Id
        {
            get { return "202003291942127_addPayment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
